// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywxburhhgezlmdmsmetv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3eGJ1cmhoZ2V6bG1kbXNtZXR2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NDAwNzMsImV4cCI6MjA3MTExNjA3M30.tyYj6_w7nu1ZvqjJvTn_ayI8ohrnhfGofQz99uQ2GZ8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});